### ISSUE TITLE
Implement Souders Rules of High Performance Websites

### ISSUE THREAD

**Issue by camwes** [ohmlabs/ohm#3]
- [ ] Make fewer HTTP requests
- [x] Use a CDN
- [x] Add an Expires header
- [x] Gzip components
- [x] Put stylesheets at the top
- [x] Move scripts to the bottom
- [ ] Caching
- [ ] CSS image sprites
- [x] Avoid CSS expressions
- [x] Make JS and CSS external
- [ ] Reduce DNS lookups
- [x] Minify JS
- [ ] Avoid redirects
- [ ] Remove duplicate scripts
- [ ] Configure ETags
- [ ] Make AJAX cacheable
